# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             []

# Build
exclude: ['Rakefile', 'README.md']

# URLs
permalink: /:title

# Meta
name: Poligeek
description: 'Le podcast Politique et Tech !'

seo_description: ""
seo_keywords: ""
