name: Poligeek
description: 'Le podcast Politique et Tech !'

# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

exclude: ['Rakefile', 'README.md']

permalink: /:title

paginate: 3
paginate_path: "page:num/"

seo_description: ""
seo_keywords: ""
