# Dependencies
markdown:        	kramdown
highlighter:     	rouge

# Build
exclude: 		    	['README.md', 'Gemfile', 'Gemfile.lock', 'validate.sh']

# URLs
permalink: 			  /:title 	# domain.com/<title>

# Meta
name: 				    Poligeek
description: 		  'Le podcast Politique et Tech !'

seo_description: 	"Poligeek, c'est le podcast qui revient toutes les deux semaines sur l'essentiel de l'actualité politique autour des nouvelles technologies. Retrouvez dans chaque épisode les news et le grand débat. Disponible un jeudi sur deux à 17h."
seo_keywords: 		"podcast,politique,technologie,geek,débat"